name: Setup Dioxus
description: Setup Dioxus environment

runs:
    using: composite
    steps:
        - uses: actions/cache@v4
          with:
              path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  ~/.dioxus/
                  target/
              key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        - shell: bash
          run: |
              sudo apt update
              sudo apt install -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
        - shell: bash
          run: cargo install --force dioxus-cli@0.7.0-alpha.3
        - shell: bash
          run: rustup target add wasm32-unknown-unknown aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
        - shell: bash
          run: touch assets/style.css
