name: Setup Dioxus
description: Setup Dioxus environment with dependencies and database configuration

runs:
    using: composite
    steps:
        - uses: actions/cache@v4
          with:
              path: |
                  ~/.cargo/
                  ~/.dioxus/
                  ~/.rustup/
                  target/
              key: ${{ runner.os }}-cargo-{{ hashFiles('**/Cargo.lock') }}
        - uses: cargo-bins/cargo-binstall@main
        - uses: awalsh128/cache-apt-pkgs-action@latest
          with:
              packages: |
                  libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
                  bubblewrap gir1.2-atk-1.0 gir1.2-atspi-2.0 gir1.2-ayatanaappindicator3-0.1 gir1.2-ayatanaido3-0.4
                  gir1.2-dbusmenu-glib-0.4 gir1.2-freedesktop gir1.2-freedesktop-dev gir1.2-gdkpixbuf-2.0 gir1.2-girepository-2.0-dev
                  gir1.2-glib-2.0-dev gir1.2-gtk-3.0 gir1.2-harfbuzz-0.0 gir1.2-javascriptcoregtk-4.1 gir1.2-pango-1.0 gir1.2-rsvg-2.0
                  gir1.2-soup-3.0 gir1.2-webkit2-4.1 glib-networking glib-networking-common glib-networking-services
                  gobject-introspection gobject-introspection-bin gsettings-desktop-schemas gstreamer1.0-plugins-base
                  gstreamer1.0-plugins-good libaa1 libasyncns0 libatk-bridge2.0-dev libatk1.0-dev libatspi2.0-dev libavc1394-0
                  libayatana-appindicator3-1 libayatana-ido3-0.4-0 libayatana-ido3-dev libayatana-indicator3-7
                  libayatana-indicator3-dev libblkid-dev libbrotli-dev libbz2-dev libcaca0 libcairo-script-interpreter2 libcairo2-dev
                  libcdparanoia0 libdatrie-dev libdbus-1-dev libdbusmenu-glib-dev libdeflate-dev libdv4t64 libegl-dev libegl-mesa0
                  libegl1 libegl1-mesa-dev libepoxy-dev libflac12t64 libfontconfig-dev libfreetype-dev libfribidi-dev libgdk-pixbuf-2.0-0
                  libgdk-pixbuf-2.0-dev libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libgirepository-1.0-dev libgirepository-2.0-0
                  libgirepository1.0-dev libgl-dev libgles-dev libgles1 libgles2 libglib2.0-dev libglib2.0-dev-bin
                  libglvnd-core-dev libglvnd-dev libglx-dev libgraphite2-dev libgstreamer-gl1.0-0 libgstreamer-plugins-base1.0-0
                  libgstreamer-plugins-good1.0-0 libgtk-3-dev libharfbuzz-cairo0 libharfbuzz-dev libharfbuzz-gobject0 libharfbuzz-icu0
                  libharfbuzz-subset0 libhyphen0 libice-dev libiec61883-0 libjavascriptcoregtk-4.1-0 libjavascriptcoregtk-4.1-dev
                  libjbig-dev libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev liblerc-dev liblzma-dev libmanette-0.2-0 libmount-dev
                  libmp3lame0 libmpg123-0t64 libnghttp2-dev libopengl-dev libopengl0 libopus0 liborc-0.4-0t64 libpango1.0-dev
                  libpangoxft-1.0-0 libpixman-1-dev libpng-dev libproxy1v5 libpsl-dev libpthread-stubs0-dev libpulse0 libraw1394-11
                  librsvg2-2 librsvg2-common libsecret-1-0 libsecret-common libselinux1-dev libsepol-dev libsharpyuv-dev libshout3
                  libsm-dev libsndfile1 libsoup-3.0-0 libsoup-3.0-common libsoup-3.0-dev libspeex1 libsysprof-capture-4-dev
                  libtag1v5 libtag1v5-vanilla libthai-dev libtheora0 libtiff-dev libtiffxx6 libtwolame0 libv4l-0t64 libv4lconvert0t64
                  libvisual-0.4-0 libvorbisenc2 libvpx9 libwavpack1 libwayland-bin libwayland-dev libwebkit2gtk-4.1-0 libwebp-dev
                  libwebpdecoder3 libwoff1 libx11-dev libxau-dev libxcb-render0-dev libxcb-shm0-dev libxcb1-dev libxcomposite-dev
                  libxcursor-dev libxdamage-dev libxdmcp-dev libxdo3 libxext-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev
                  libxkbcommon-dev libxrandr-dev libxrender-dev libxtst-dev pango1.0-tools python3-mako python3-markdown
                  session-migration uuid-dev wayland-protocols x11proto-dev xdg-dbus-proxy xorg-sgml-doctools xtrans-dev
              version: 1.0
        - name: Install system dependencies
          shell: bash
          run: |
              sudo apt update
              sudo apt install --yes --no-install-recommends --no-install-suggests \
                  libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
        - name: Install Dioxus CLI & SQLx CLI
          shell: bash
          run: cargo binstall -y dioxus-cli@0.7.0-alpha.3 sqlx-cli@0.8.6
        - name: Add additional RustUp targets
          shell: bash
          run: rustup target add wasm32-unknown-unknown aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
        - name: Run database migrations
          shell: bash
          run: sqlx database setup
        - shell: bash
          run: touch assets/style.css
