[package]
name = "lime3"
version = "0.0.0-alpha.0"
authors = ["Javier E. <jaedns@gmail.com>"]
edition = "2024"

[dependencies]
argon2 = { version = "0.5.3", optional = true }
chrono = { version = "0.4.41", features = ["serde"] }
dioxus = { version = "0.7.0-alpha.3", features = ["router", "fullstack"] }
figment = { version = "0.10.19", features = ["env"], optional = true }
regex = { version = "1.11.1", optional = true }
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8.6", features = [
    "chrono",
    "postgres",
    "runtime-tokio",
    "uuid",
], optional = true }
tokio = { version = "1.47.0", optional = true }
uuid = { version = "1.17.0", optional = true }
validator = "0.20.0"

[dev-dependencies]
dioxus-ssr = "0.7.0-alpha.3"
fake = "4.3.0"
pretty_assertions = "1.4.1"
rand = "0.9.2"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = [
    "dep:argon2",
    "dep:figment",
    "dep:regex",
    "dep:sqlx",
    "dep:tokio",
    "dep:uuid",
    "dioxus/server",
    "validator/derive",
]
