[package]
name = "lime3"
version = "0.0.0-alpha.0"
authors = ["Javier E. <jaedns@gmail.com>"]
edition = "2024"

[dependencies]
dioxus = { version = "0.7.0-alpha.3", features = ["router", "fullstack"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
dioxus-ssr = "0.7.0-alpha.3"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
