[package]
name = "lime3-cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap = "4.5.46"
serde_json = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
lime3-core = { workspace = true, features = ["server"] }
