[package]
name = "lime3-cli"
version.workspace = true
edition.workspace = true

[dependencies]
bytesize = { workspace = true }
clap = "4.5.46"
tokio = { workspace = true }
lime3-core = { workspace = true, features = ["server"] }
