name: CI/CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    code_analysis:
        uses: ./.github/workflows/code-analysis.yaml

    tests:
        needs: [code_analysis]
        uses: ./.github/workflows/tests.yaml

    build:
        needs: [tests]
        uses: ./.github/workflows/build.yaml

    deploy:
        needs: [build]
        # if: github.ref == 'refs/heads/main'
        uses: ./.github/workflows/deploy.yaml
        with:
            deploy_script: ${{ secrets.DEPLOY_SCRIPT }}
