name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    code_analysis:
        uses: ./.github/workflows/code-analysis.yaml

    build:
        needs: [code_analysis]
        uses: ./.github/workflows/build.yaml

    tests:
        needs: [build]
        uses: ./.github/workflows/tests.yaml
